import React, { useState } from 'react';

const AddressBookPage = () => {
    const [addresses, setAddresses] = useState([{ id: 1, name: 'Home', street: '123 Fashion St', city: 'New York', state: 'NY', zipCode: '10001', country: 'US', isDefault: true }]);
    const [showForm, setShowForm] = useState(false);
    const [newAddress, setNewAddress] = useState({ name: '', street: '', city: '', state: '', zipCode: '', country: 'US' });

    const handleAdd = (e) => { e.preventDefault(); setAddresses([...addresses, { ...newAddress, id: Date.now(), isDefault: false }]); setNewAddress({ name: '', street: '', city: '', state: '', zipCode: '', country: 'US' }); setShowForm(false); };
    const setDefault = (id) => { setAddresses(addresses.map(addr => ({ ...addr, isDefault: addr.id === id }))); };
    const deleteAddress = (id) => { setAddresses(addresses.filter(addr => addr.id !== id)); };

    return (
        <div className="bg-gray-50 min-h-screen py-12"><div className="max-w-4xl mx-auto px-4"><div className="flex justify-between items-center mb-8"><h1 className="text-4xl font-light">Address Book</h1><button onClick={() => setShowForm(true)} className="px-4 py-2 bg-black text-white rounded-lg">+ Add Address</button></div><div className="space-y-4">{addresses.map(addr => (<div key={addr.id} className="bg-white rounded-lg p-4 flex justify-between"><div><p className="font-semibold">{addr.name}</p><p className="text-gray-600 text-sm">{addr.street}, {addr.city}, {addr.state} {addr.zipCode}</p>{addr.isDefault && <span className="inline-block mt-1 text-xs bg-gray-200 px-2 py-1 rounded">Default</span>}</div><div className="flex gap-2">{!addr.isDefault && <button onClick={() => setDefault(addr.id)} className="text-sm text-gray-500">Set Default</button>}<button onClick={() => deleteAddress(addr.id)} className="text-sm text-red-500">Delete</button></div></div>))}</div>{showForm && (<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"><div className="bg-white rounded-lg p-6 w-full max-w-md"><h2 className="text-xl font-semibold mb-4">Add Address</h2><form onSubmit={handleAdd} className="space-y-3"><input type="text" placeholder="Name (Home, Office)" value={newAddress.name} onChange={(e) => setNewAddress({...newAddress, name: e.target.value})} className="w-full px-3 py-2 border rounded-lg" required /><input type="text" placeholder="Street Address" value={newAddress.street} onChange={(e) => setNewAddress({...newAddress, street: e.target.value})} className="w-full px-3 py-2 border rounded-lg" required /><div className="grid grid-cols-2 gap-3"><input type="text" placeholder="City" value={newAddress.city} onChange={(e) => setNewAddress({...newAddress, city: e.target.value})} className="px-3 py-2 border rounded-lg" required /><input type="text" placeholder="State" value={newAddress.state} onChange={(e) => setNewAddress({...newAddress, state: e.target.value})} className="px-3 py-2 border rounded-lg" required /></div><div className="grid grid-cols-2 gap-3"><input type="text" placeholder="Zip Code" value={newAddress.zipCode} onChange={(e) => setNewAddress({...newAddress, zipCode: e.target.value})} className="px-3 py-2 border rounded-lg" required /><select value={newAddress.country} onChange={(e) => setNewAddress({...newAddress, country: e.target.value})} className="px-3 py-2 border rounded-lg"><option value="US">US</option><option value="CA">Canada</option></select></div><div className="flex gap-3 mt-4"><button type="submit" className="flex-1 bg-black text-white py-2 rounded-lg">Save</button><button type="button" onClick={() => setShowForm(false)} className="flex-1 border py-2 rounded-lg">Cancel</button></div></form></div></div>)}</div></div>
    );
};

export default AddressBookPage;
